
# in case we need to specify cron in config file of Netlify

[functions."schedular_function"]
schedule = "* * * * *"

# scheduled functions configuration

[dev]
functions = "schedular"
functionsPort = 7000